# @format

on: 'push'
name: GitX
jobs:
  build:
    name: Build GitX.app
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set XCode Version
        run: sudo xcode-select -s /Applications/${{ matrix.xcode }}.app
      - name: pre build
        run: cd External/objective-git && script/bootstrap && script/update_libgit2 && cd ../..
      - name: Build project
        run: set -o pipefail && xcodebuild -workspace GitX.xcworkspace -scheme GitX archive | xcpretty
      - uses: actions/upload-artifact@v2
        with:
          name: build-directory
          path: /Users/runner/work/gitx/gitx/build
